[plugins.opt]
  path = "/volume1/k3s/agent/containerd"

[debug]
  level = "debug"

[plugins.cri.containerd]
  snapshotter = "native"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"

[plugins.cri.cni]
  bin_dir = "/volume1/k3s/data/31f16867327c45f309297f2846b7f471edba2b97c394cddb49d4e70ff7d41bcd/bin"
  conf_dir = "/volume1/k3s/agent/etc/cni/net.d"
